
services:

    fedstellar-frontend:
        container_name: fedstellar-frontend
        image: fedstellar-frontend
        build: .
        restart: unless-stopped
        volumes:
            - /Users/enrique/Documents/PhD/fedstellar:/fedstellar
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config/fedstellar:/etc/nginx/sites-available/default
            - ./start_services.sh:/start_services.sh
        environment:
            - SERVER_LOG=/fedstellar/app/logs/server.log
            - FEDSTELLAR_LOGS_DIR=/fedstellar/app/logs/
            - FEDSTELLAR_CONFIG_DIR=/fedstellar/app/config/
            - FEDSTELLAR_MODELS_DIR=/fedstellar/app/models/
            - FEDSTELLAR_ENV_PATH=/fedstellar/app/.env
            - FEDSTELLAR_ROOT_HOST=/Users/enrique/Documents/PhD/fedstellar
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ipc: host
        privileged: true
        ports:
            - 6060:80
            - 6065:8080
        networks:
            fedstellar-net-base:
                ipv4_address: 192.168.100.100


networks:
    fedstellar-net-base:
        name: fedstellar-net-base
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.100.1/24
                  gateway: 192.168.100.1
